# fly.toml app configuration file generated for mybpm on 2023-05-14T23:12:03-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mybpm"
primary_region = "gru"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  APP_NAME = "MyBPM"
  APP_KEY = "base64:YxVZ4lllhcnrcne2ht7ZFhErvuZI502MXf0MiHV1C08="
  APP_DEBUG = "false"
  APP_URL = "https://mybpm.fly.dev"
  DB_CONNECTION = "pgsql"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"
